
version: '3.8'

services:
  api-gateway:
    build: ./server/api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./server/api-gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DASHBOARD_SERVICE_URL=http://dashboard-service:3001
      - QUESTIONS_SERVICE_URL=http://questions-service:3002
      - CREATOR_SERVICE_URL=http://creator-service:3003
    networks:
      - learnify-network
    depends_on:
      - dashboard-service
      - questions-service
      - creator-service
    restart: unless-stopped

  dashboard-service:
    build: ./server/dashboard
    ports:
      - "3001:3001"
    volumes:
      - ./server/dashboard:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - learnify-network
    restart: unless-stopped

  questions-service:
    build: ./server/questions
    ports:
      - "3002:3002"
    volumes:
      - ./server/questions:/app
      - ./server/questions/data:/app/data
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DB_PATH=/app/data/questions.json
    networks:
      - learnify-network
    restart: unless-stopped

  creator-service:
    build: ./server/creator
    ports:
      - "3003:3003"
    volumes:
      - ./server/creator:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3003
      - QUESTIONS_SERVICE_URL=http://questions-service:3002
    networks:
      - learnify-network
    depends_on:
      - questions-service
    restart: unless-stopped

  frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_GATEWAY=http://localhost:3000/api
    networks:
      - learnify-network
    depends_on:
      - api-gateway
    restart: unless-stopped

networks:
  learnify-network:
    driver: bridge
