
version: '3.8'

services:
  api-gateway:
    build: ./server/api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./server/api-gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DASHBOARD_SERVICE_URL=http://dashboard-service:3001
      - QUESTIONS_SERVICE_URL=http://questions-service:3002
      - CREATOR_SERVICE_URL=http://creator-service:3003
    networks:
      - learnify-network
    depends_on:
      - dashboard-service
      - questions-service
      - creator-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  dashboard-service:
    build: ./server/dashboard
    volumes:
      - ./server/dashboard:/app
      - ./server/dashboard/data:/app/data
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_PATH=/app/data/dashboard.json
    networks:
      - learnify-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  questions-service:
    build: ./server/questions
    volumes:
      - ./server/questions:/app
      - ./server/questions/data:/app/data
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DB_PATH=/app/data/questions.json
    networks:
      - learnify-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  creator-service:
    build: ./server/creator
    volumes:
      - ./server/creator:/app
      - ./server/creator/data:/app/data
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3003
      - QUESTIONS_SERVICE_URL=http://questions-service:3002
      - DB_PATH=/app/data/creator.json
    networks:
      - learnify-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      - questions-service

  frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_GATEWAY=http://localhost:3000/api
    networks:
      - learnify-network
    depends_on:
      - api-gateway
    restart: unless-stopped

networks:
  learnify-network:
    driver: bridge
